chore: remove names of companies & projects in "Growing adoption.."
gitops-working-group/gitops-working-group pull request #117
Opened 2021-03-31 00:40 UTC by sbose78

I would like to propose we avoid using names of companies & projects in the "Growing adoption of GitOps" to ensure the group's promise to technology/vendor neutrality isn't diluted :) 

Note, the names of the founding members ( a huge thanks to the initiative ) is already present in the Timeline section.

Disclosure: 
I work for Red Hat, contribute to Argo and I love running Flux on OpenShift deployed on AWS :)

2021-06-01 14:48 UTC, sbose78 commented
@scottrigby Looks good!

2021-06-01 15:24 UTC, scottrigby commented
@sbose78 OK just need to amend your commit to add your DCO signoff (see https://github.com/gitops-working-group/gitops-working-group/pull/117/checks).

PS, you may be interested in this fun plugin I made to help with this when using the GitHub UI 😸 https://github.com/scottrigby/dco-gh-ui/

I made this because this issue eventually happens to almost everyone contributing to CNCF/LF projects that require DCO.

2021-10-09 03:43 UTC, lloydchang approved these changes

2021-10-09 03:47 UTC, lloydchang commented
@sbose78 We need a DCO sign-off; please see https://github.com/gitops-working-group/gitops-working-group/pull/117#issuecomment-852216292 Thank you!

@scottrigby @todaywasawesome Since Git `Signed-off-by:` can be a different person than the Git commit author — If you want to DCO sign-off this for @sbose78, then that should be fine too.

Thank you, everyone!

2021-10-09 03:49 UTC, scottrigby commented
Hey @lloydchang i believe this was addressed in a different way in #167, so we should close this now

2021-10-09 03:58 UTC, lloydchang requested changes
Please close this in favor of https://github.com/gitops-working-group/gitops-working-group/pull/167 because of https://github.com/gitops-working-group/gitops-working-group/pull/117#issuecomment-939218611

2021-10-09 04:25 UTC, sbose78 commented
Sure thing, thanks!

2021-10-09 04:25 UTC, closed without merging