Update interested-parties.md with Graeme Hay and Erick Bourgeois from Morgan Stanley
gitops-working-group/gitops-working-group pull request #169
Opened 2021-10-12 20:49 UTC by grmhay

2021-10-13 14:47 UTC, lloydchang commented
@grmhay @ebourgeois  Generally re: DCO, I found the the following useful.  Thank you!

@scottrigby wrote in https://github.com/gitops-working-group/gitops-working-group/pull/117
>  just need to amend your commit to add your DCO signoff
>
> PS, you may be interested in this fun plugin I made to help with this when using the GitHub UI 😸 https://github.com/scottrigby/dco-gh-ui/
>
> I made this because this issue eventually happens to almost everyone contributing to CNCF/LF projects that require DCO.

2021-10-13 17:11 UTC, grmhay commented
Thanks - will check that out

On Wed, Oct 13, 2021 at 7:47 AM lloydchang ***@***.***> wrote:

> @grmhay <https://github.com/grmhay> @ebourgeois
> <https://github.com/ebourgeois> Generally re: DCO, I found the the
> following useful. Thank you!
>
> @scottrigby <https://github.com/scottrigby> wrote in #117
> <https://github.com/gitops-working-group/gitops-working-group/pull/117>
>
> just need to amend your commit to add your DCO signoff
>
> PS, you may be interested in this fun plugin I made to help with this when
> using the GitHub UI 😸 https://github.com/scottrigby/dco-gh-ui/
>
> I made this because this issue eventually happens to almost everyone
> contributing to CNCF/LF projects that require DCO.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/gitops-working-group/gitops-working-group/pull/169#issuecomment-942381627>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABWZDONK2KVYIA5R7G44WU3UGWLXPANCNFSM5F3RQZSA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-10-17 15:56 UTC, lloydchang requested changes

2021-10-17 15:56 UTC, lloydchang commented on interested-parties.md
> +Morgan Stanley | Graeme Hay
Thanks @ebourgeois and @grmhay — A tip similar to https://github.com/gitops-working-group/gitops-working-group/pull/170#pullrequestreview-780057521
> Hi! Welcome! Could you add your GitHub username next to your name - we had not done this with previous interested parties and then realized we really had no efficient way to be able to reach out to all of you so I want to make sure we start fixing that ;)

2022-01-17 06:48 UTC, scottrigby commented
Hi @grmhay and @ebourgeois - would you please make a new PR adding yourself to [interested-parties.md](https://github.com/cncf/tag-app-delivery/blob/main/gitops-wg/interested-parties.md) in the GitOps WG new location under the App Delivery TAG repo?
Thanks!

2022-01-17 06:48 UTC, closed without merging