Updating Draft Definition with the correct link
gitops-working-group/gitops-working-group pull request #2
Opened 2020-12-15 18:55 UTC by dj1k

Signed-off-by: Daniel Lizio-Katzen <daniel@djlk.com>

2020-12-16 17:21 UTC, bricef approved these changes

2020-12-18 03:08 UTC, cdavisafc commented
@dj1k I would suggest cleaning up the link ever so slightly to get rid of the ts part at the end.

2020-12-18 03:19 UTC, cdavisafc requested changes
@dj1k I would suggest cleaning up the link ever so slightly to get rid of the ts part at the end.

2020-12-18 13:26 UTC, dj1k reviewed
all set - removed everything after the ?

2021-01-21 10:55 UTC, closed without merging