Updated Meetings.md
gitops-working-group/gitops-working-group pull request #58
Opened 2021-02-15 22:04 UTC by tonit

Added Recording Link for call on Feb 11th.
Also added a hint on the probably general monthly cadence of those meetings.

2021-02-16 07:29 UTC, chrisk700 commented on MEETINGS.md
> +[Video Recording](https://weaveworks.zoom.us/rec/share/OPy5MSMzgIkPX1-PAdhwrnGGa82Lr5BuVpQ1iSK-sbHPph68ML1JNVQXRKlP09bw.bjqDnPKEA2W9D2HG)<br>
Should the date/time be added as per the other recordings?

i.e. Thursday, February 11th at 18:00 GMT

2021-02-18 17:00 UTC, todaywasawesome requested changes

2021-02-18 17:00 UTC, todaywasawesome commented on MEETINGS.md
> +Proposed next meeting: We need to pick regular monthly cadence to be on CNCF calendar -2nd thursday 6pm GMT
We do have a monthly cadence which is the 2nd Thursday 6pm GMT as you point out.

2021-02-19 08:04 UTC, tonit commented
Upcomings updated to reflect what we know: "every 2nd Thursday 6pm GMT". Is there a link to a cncf calendar entry & fixed meeting link?

2021-02-27 00:28 UTC, cdavisafc commented
I'm drawing these changes and those from PR #60 into a new consolidated one.

2021-02-27 00:28 UTC, closed without merging

2021-02-27 09:37 UTC, tonit commented
Thanks for heads-up, @cdavisafc 👍🏼